### ISSUE TITLE
Rename to ndarray-gemm?

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-gemm#1]
Totally trivial, but maybe for the sake of consistency. No strong preference here; just a thought as I sweep through and aim for cleanup.

**Comment by rreusser** [comment]
Sidenote: Dependents are:
- mikolalysenko-hoarders
- crunch-js
- @williamle8300/boilerplate
- my-npm-boilerplate
- ndarray-bundle

so, although there are certainly unpublished packages that use ndgemm, it's maybe not so strongly-depended upon that changing the name would break a whole community.

**Comment by mikolalysenko** [comment]
Yeah, I think this is a good idea, so :+1:

**Comment by rreusser** [comment]
Moved.
